/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ebaec512-1d5c-4aad-ad20-33b2e6af4db0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Rs8UDvfpO",
    "aws_user_pools_web_client_id": "47cpih4ho6bdi0kabpbjnbe9if",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fcsctezgbrfdxlaif33pq74n64.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
